---
- name: Controller | Copy kube-apiserver.service
  template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
    mode: 0644
  notify:
    - restart kube-apiserver

- name: Controller | Copy kube-controller-manager.service
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
    mode: 0644
  notify:
    - restart kube-controller-manager

- name: Controller | Copy kube-scheduler.service
  template:
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
    mode: 0644
  notify:
    - restart kube-scheduler
