---
- name: Loadbalancer | Install confd
  get_url:
    url: "https://github.com/kelseyhightower/confd/releases/download/v{{ confd_version }}/confd-{{ confd_version }}-linux-amd64"
    dest: /usr/bin/confd
    mode: 0700

- name: Loadbalancer | Move onetime-confd.sh script
  template:
    src: onetime-confd.sh
    dest: /opt/onetime-confd.sh
    mode: 0777

- name: Loadbalancer | Make sure /etc/confd/conf.d exists
  file:
    path: /etc/confd/conf.d
    state: directory

- name: Loadbalancer | Make sure /etc/confd/templates exists
  file:
    path: /etc/confd/templates
    state: directory

- name: Loadbalancer | Move nginx.toml for confd
  template:
    src: nginx.toml.j2
    dest: /etc/confd/conf.d/nginx.toml
  notify: restart confd

- name: Loadbalancer | Move nginx.tmpl for nginx.toml
  template:
    src: nginx.tmpl.j2
    dest: /etc/confd/templates/nginx.tmpl
  notify: restart confd

- name: Loadbalancer | Move template confd.service
  template:
    src: confd.service.j2
    dest: /etc/systemd/system/confd.service
  notify: restart confd
