---
- name: Loadbalancer | Check if kontinuum-lb container is running
  register: kontinuum_lb_running
  raw: docker ps | grep -q kontinuum-lb
  ignore_errors: true

- name: Loadbalancer | Check if kontinuum-lb container is in images
  register: kontinuum_lb_exists
  raw: docker ps -a | grep -q kontinuum-lb
  ignore_errors: true

- name: Loadbalancer | Remove kontinuum-lb image
  command: "{{ item }}"
  with_items:
    - docker stop kontinuum-lb
    - docker rm kontinuum-lb
  when: kontinuum_lb_running.rc == 1 and kontinuum_lb_exists.rc == 0

- name: Loadbalancer | Run kontinuum-lb container
  command: docker run -d -p 80:80 \
    --name kontinuum-lb \
    --restart on-failure:5 \
    -e DOMAIN={{ domain_name }} \
    --net="host" \
    esayemm/kontinuum-loadbalancer
  when: kontinuum_lb_running | failed
