---
- name: Loadbalancer | Make sure /etc/nginx/sites-enabled exists
  file:
    path: /etc/nginx/sites-enabled
    state: directory

- name: Loadbalancer | Move nginx.conf to /etc/nginx/nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Loadbalancer | Check if nginx container is running
  register: nginx_running
  raw: docker ps | grep -q nginx
  ignore_errors: true

- name: Loadbalancer | Check if nginx container is in images
  register: nginx_container_exists
  raw: docker ps -a | grep -q nginx
  ignore_errors: true

- name: Loadbalancer | Remove nginx image
  command: "{{ item }}"
  with_items:
    - docker stop nginx
    - docker rm nginx
  when: nginx_running.rc == 1 and nginx_container_exists.rc == 0

- name: Loadbalancer | Run nginx docker container
  command: docker run --name nginx -d -p 80:80 \
    -v /etc/nginx/nginx.conf:/etc/nginx/nginx.conf \
    -v /etc/nginx/sites-enabled:/etc/nginx/sites-enabled \
    nginx
  when: nginx_running | failed
