---
- name: ensure folder for certs exists
  file:
    path: "{{ optdest }}/certs"
    state: directory

- name: move ca.pem
  copy:
    src: ../../certs/ca.pem
    dest: "{{ optdest }}/certs/ca.pem"

- name: move ca-key.pem
  copy:
    src: ../../certs/ca-key.pem
    dest: "{{ optdest }}/certs/ca-key.pem"

- name: move template generate-certs.sh
  template:
    src: ../scripts/generate-certs.sh.j2
    dest: "{{ optdest }}/generate-certs.sh"
    mode: 0700

- name: run generate-certs.sh
  shell: "{{ optdest }}/generate-certs.sh"
