---
- name: unarchive flannel
  get_url:
    url: https://www.github.com/coreos/flannel/releases/download/{{flannel_version}}/flannel-{{flannel_version}}-linux-amd64.tar.gz
    dest: /opt

- name: move flannel binary to /usr/bin
  command: "{{ item }}"
  with_items:
    - tar xf /opt/flannel-{{flannel_version}}-linux-amd64.tar.gz -C /opt
    - mv /opt/flanneld /usr/bin/flanneld

- name: template flannel.service
  template:
    src: ../services/flannel.service.j2
    dest: /etc/systemd/system/flannel.service
    mode: 0644
  notify:
    - reload flannel

- name: start flannel service
  service:
    name: flannel
    state: started
