---
- name: register variable etcdctl_installed
  register: etcdctl_installed
  command: etcdctl -v
  ignore_errors: true

- name: unarchive etcdctl binary
  unarchive:
    src: "https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    dest: /opt
    copy: no
  when: etcdctl_installed|failed

- name: mv etcdctl binary to /usr/bin
  command: "{{ item }}"
  with_items:
    - mv /opt/etcd-{{ etcd_version }}-linux-amd64/etcdctl /usr/bin
  when: etcdctl_installed|failed

- name: move set-cluster-cidr.sh
  template:
    src: ../scripts/set-cluster-cidr.sh.j2
    dest: "{{ optdest }}/set-cluster-cidr.sh"
    mode: 0700

- name: run set-cluster-cidr.sh
  shell: "{{ optdest }}/set-cluster-cidr.sh"
