---
- name: register variable etcdctl_installed
  register: etcdctl_installed
  command: which etcdctl
  ignore_errors: true

- name: unarchive etcdctl binary
  unarchive:
    src="https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    dest=/opt
    copy=no
  when: etcdctl_installed|failed

- name: mv etcdctl binary to /usr/bin
  command: "{{ item }}"
  with_items:
    - mv /opt/etcd-{{ etcd_version }}-linux-amd64/etcdctl /usr/bin
  notify:
    - reload etcd
  when: etcdctl_installed|failed

- name: set ETCDCTL_API=2 in environment
  lineinfile: dest=/etc/environment regexp=^ETCDCTL_API line=ETCDCTL_API=2

# Allows etcdctl to work without passing in --ca-file --cert-file --key-file
- lineinfile: dest=/etc/environment regexp=^ETCDCTL_CA_FILE line=ETCDCTL_CA_FILE={{ optdest }}/certs/ca.pem
- lineinfile: dest=/etc/environment regexp=^ETCDCTL_CERT_FILE line=ETCDCTL_CERT_FILE={{ optdest }}/certs/{{ certfilename }}
- lineinfile: dest=/etc/environment regexp=^ETCDCTL_KEY_FILE line=ETCDCTL_KEY_FILE={{ optdest }}/certs/{{ keyfilename }}

- template: src=../scripts/set-cluster-cidr.sh.j2
    dest={{ optdest }}/set-cluster-cidr.sh
    mode=0700
- command: "{{ optdest }}/set-cluster-cidr.sh"
