---
- name: Etcd | Check if cluster is healthy
  shell: "etcdctl --peers={{ etcd_peers }} cluster-health | grep -q 'cluster is healthy'"
  register: etcd_cluster_is_healthy
  ignore_errors: true
  changed_when: false

- name: Etcd | Check if member is in cluster
  shell: "etcdctl --no-sync --peers={{ etcd_peers }} member list | grep -q {{ hostvars[inventory_hostname]['ipv4_address_private'] }}"
  register: etcd_member_in_cluster
  ignore_errors: true
  changed_when: false

- name: Etcd | Add member to the cluster if it is not there
  when: etcd_member_in_cluster.rc != 0 and etcd_cluster_is_healthy.rc == 0
  shell: "etcdctl --peers={{ etcd_peers }} member add {{ hostvars[inventory_hostname]['name'] }} https://{{ hostvars[inventory_hostname]['ipv4_address_private'] }}:2380"

- name: Etcd | Copy etcd.service systemd file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: 0644
  notify: restart etcd

- name: Etcd | Copy etcd.env file
  template:
    src: etcd.env.j2
    dest: /etc/etcd.env
  notify: restart etcd
