---
- name: Etcd | Copy etcd.env file
  template:
    src: etcd-proxy.env.j2
    dest: "{{ env_folder }}/etcd.env"
  notify: restart etcd

- name: Etcd | Copy etcd.service systemd file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: 0644
  notify: restart etcd
