---
- name: Worker | Make sure /opt/cni exists
  file:
    path: /opt/cni
    state: directory

- name: Worker | Unarchive cni
  unarchive:
    src: "https://storage.googleapis.com/kubernetes-release/network-plugins/cni-07a8a28637e97b22eb8dfe710eeae1344f69d16e.tar.gz"
    dest: /opt/cni
    copy: no
