---
- name: Set Fact | certs_folder
  set_fact:
    certs_folder: /opt/certs

- name: Set Fact | certs_keyfile, certs_certfile
  set_fact:
    certs_keyfile: "{{certs_folder}}/cluster.key"
    certs_certfile: "{{certs_folder}}/cluster.crt"

- name: Set Fact | global variables
  set_fact:
    env_folder: /opt/env

    kube_version: 'v1.4.0'
    kube_cluster_name: "cluster.local"
    kube_service_ip_range: '10.32.0.0/24'
    kube_cluster_dns: '10.32.0.10'
    kube_pods_subnet: '10.200.0.0/16'
    flannel_version: 'v0.6.2'

    is_etcd_master: "{{ inventory_hostname in groups['etcd'] }}"
    is_etcd_proxy: "{{ inventory_hostname not in groups['etcd'] }}"

    etcd_peers: |-
      {% for host in groups['etcd'] -%}
        https://{{ hostvars[host]['ipv4_address_private'] }}:2379{% if not loop.last %},{% endif %}
      {%- endfor %}

    etcd_hosts: |-
      {% for host in groups['etcd'] -%}
        https://{{ hostvars[host]['ipv4_address_private'] }}:2380{% if not loop.last %},{% endif %}
      {%- endfor %}

    # use with etcd --initial-cluster
    etcd_hosts_named: |-
      {% for host in groups['etcd'] -%}
        {{ hostvars[host]['name'] }}=https://{{ hostvars[host]['ipv4_address_private'] }}:2380{% if not loop.last %},{% endif %}
      {%- endfor %}

    kube_controller_ip: |-
      {% for host in groups['kube-controller'] -%}
        https://{{ hostvars[host]['ipv4_address_private'] }}:6443
      {%- endfor %}
