---
- hosts: kube-controller
  # serial: '50%'
  become: true
  gather_facts: False
  vars:
    kubernetes_version: 'v1.4.0'

  handlers:
    - name: reload kube-apiserver
      command: "{{ item }}"
      with_items:
        - systemctl daemon-reload
        - systemctl restart kube-apiserver

    - name: reload kube-controller-manager
      command: "{{ item }}"
      with_items:
        - systemctl daemon-reload
        - systemctl restart kube-controller-manager

    - name: reload kube-scheduler
      command: "{{ item }}"
      with_items:
        - systemctl daemon-reload
        - systemctl restart kube-scheduler

  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    ##########################################################################
    # certs
    ##########################################################################

    - file: path=/etc/kubernetes/certs state=directory
    - copy: src=../../certs/ca.pem dest=/etc/kubernetes/certs/ca.pem
    - copy: src=../../certs/ca-key.pem dest=/etc/kubernetes/certs/ca-key.pem
    - copy: src=../../certs/admin.crt dest=/etc/kubernetes/certs/admin.crt
    - copy: src=../../certs/admin.key dest=/etc/kubernetes/certs/admin.key
    - template: src=./scripts/generate-certs.sh.j2 dest=/etc/kubernetes/generate-certs.sh mode=0700
    - shell: /etc/kubernetes/generate-certs.sh

    - copy: src=./auth/token.csv dest=/etc/kubernetes/certs/
    - copy: src=./auth/authorization-policy.jsonl dest=/etc/kubernetes/certs/

    ##########################################################################
    # etcd
    ##########################################################################

    - name: unarchive etcd binary
      unarchive:
        src="https://github.com/coreos/etcd/releases/download/v3.0.10/etcd-v3.0.10-linux-amd64.tar.gz"
        dest=/opt
        copy=no

    - name: mv etcd binary to /usr/bin
      command: "{{ item }}"
      with_items:
        - mv /opt/etcd-v3.0.10-linux-amd64/etcd /usr/bin
        - mv /opt/etcd-v3.0.10-linux-amd64/etcdctl /usr/bin

    - name: set ETCDCTL_API=3 in environment
      lineinfile: dest=/etc/environment regexp=^ETCDCTL_API line=ETCDCTL_API=3

    ##########################################################################
    # download kube binaries
    ##########################################################################

    - name: download kubectl
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/{{kubernetes_version}}/bin/linux/amd64/kubectl
        dest: /usr/bin/kubectl
        mode: 0700

    - name: download kube-apiserver
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/{{kubernetes_version}}/bin/linux/amd64/kube-apiserver
        dest: /usr/bin/kube-apiserver
        mode: 0700

    - name: download kube-controller-manager
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/{{kubernetes_version}}/bin/linux/amd64/kube-controller-manager
        dest: /usr/bin/kube-controller-manager
        mode: 0700

    - name: download kube-scheduler
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/{{kubernetes_version}}/bin/linux/amd64/kube-scheduler
        dest: /usr/bin/kube-scheduler
        mode: 0700

    ##########################################################################
    # kube services
    ##########################################################################

    - name: template kube-apiserver.service
      template: src=./services/kube-apiserver.service.j2
        dest=/etc/systemd/system/kube-apiserver.service
        mode=0644
      notify:
        - reload kube-apiserver

    - name: template kube-controller-manager.service
      template: src=./services/kube-controller-manager.service.j2
        dest=/etc/systemd/system/kube-controller-manager.service
        mode=0644
      notify:
        - reload kube-controller-manager

    - name: template kube-scheduler.service
      template: src=./services/kube-scheduler.service.j2
        dest=/etc/systemd/system/kube-scheduler.service
        mode=0644
      notify:
        - reload kube-scheduler
