---
- hosts: etcd
  # serial: '50%'
  become: true
  gather_facts: False
  vars:
    etcd_version: 'v3.0.10'
    optdest: '/etc/etcd'
    certfilename: 'etcd.crt'
    keyfilename: 'etcd.key'

  tasks:
    - include: ./tasks/certs.yml
    - include: ./tasks/etcd.yml
    - name: start etcd.service
      service: name=etcd state=started

  handlers:
    - include: ./handlers/handlers.yml
