---
- hosts: etcd
  # serial: '50%'
  become: true
  gather_facts: False
  vars:
    etcd_version: 'v3.0.10'
    optdest: '/etc/etcd'
    certfilename: 'etcd.crt'
    keyfilename: 'etcd.key'

  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - include: ./tasks/certs.yml

    - include: ./tasks/etcd-task.yml

  handlers:
    - include: ./handlers/handlers.yml
